maths/find_max_recursion.dart
maths/find_min_recursion.dart

Find max/min value using divide-and-conquer algorithm

find max/min recursion

---

maths/lu_decomposition.dart

Plus example usages - solving linear equations, linear regression (ordinary least square).

Add LU decomposition implementation

---

README.md

Added the links for the images and wikis at the bottom. Coders can now see the images and wikis for the Algorithms that are briefly explained, which couldn't be possible previously.

Update README.d to show image and wiki for algorithms

---

maths/sieve_of_eratosthenes.dart

Added Sieve of Eratosthenes

---

maths/eulers_totient.dart

Added Euler's Totient (Phi function)

---

DIRECTORY.md
conversions/Decimal_To_Any.dart

Added Decimal To Any algorithm

---

sort/comb_sort.dart

Implementation of Comb sort in the dart programming language

comb_sort.dart

---

project_euler/problem_4/sol4.dart
project_euler/problem_5/sol5.dart

- project euler problem 4 and 5 solved

---

project_euler/problem_6/sol6.dart

Project Euler Problem 6 solved

---

sort/merge_sort.dart

Added merge sort

---

sort/merge_sort.dart

Bug fix in Merge Sort

---

project_euler/problem_7/sol7.dart
strings/reverse_string.dart

problem 7 solved + string reversing

---

README.md

Proper definition , visualization and links for merge sort have been added to the readme file

Added Merge sort in the Readme.md

---

project_euler/problem_9/sol9.dart

Solution problem 9

---

project_euler/problem_17/sol17.dart

Project Euler Problem 17 solved

---

.travis.yml
DIRECTORY.md
data_structures/HashMap/Hashing.dart
data_structures/Heap/Binary_Heap/Min_Heap.dart
maths/factorial_recursion.dart

Travis CI: test, dartanalyzer, and dartfmt

---

.github/workflows/dart_test_analyze_format.yml
conversions/Decimal_To_Any.dart

GitHub Action: dart format --set-exit-if-changed .

---

.github/workflows/dart_test_analyze_format.yml
analysis_options.yaml

analyzer: exclude: maths/fermats_little_theorem.dart

---

DIRECTORY.md
data_structures/binary_tree/binary_tree_traversal.dart

Implemented Binary tree DS
implemented the inOrder, postOrder, and preOrder traversal of the tree
added test cases.

Binary tree Traversal

---

DIRECTORY.md
strings/knuth_morris_prat.dart

Implemented a new file with tests for Knuth Morris pratt algorithm
Added test cases both positive and negative

DART implementation Knuth Morris Pratt Algorithm

---

DIRECTORY.md
data_structures/Heap/Binary_Heap/min_heap_two.dart

Added more methods and functions for the minheap ds
created tests

Min Heap implementation DART

---

DIRECTORY.md
dynamic_programming/coin_change.dart

Adding the Famous DP problem of coin change
where we are given a target amount and an array which consists of the coin denominations we have.
we have to find the minimum number of coins required to make the amount
Note: I have used 10^12 as int max in this case as I was reluctant to use double.infinity

Coin change (Dynamic programming problem)

---

data_structures/linked_list/cycle_in_linked_list.dart

Added the tortoise hare algorithm/ Floyds Algorithm for loop detection in LinkedList
Added multiple verifying test cases.

Floyd's Algorithm for detecting loop in LinkedList

---

DIRECTORY.md
conversions/binary_to_octal.dart

Added binary to octal conversion

---

DIRECTORY.md
conversions/binary_to_hexadecimal.dart

Added binary to hexadecimal conversion

---

DIRECTORY.md
conversions/hexadecimal_to_binary.dart

Added hexadecimal to binary conversion

---

DIRECTORY.md
conversions/octal_to_binary.dart

Added octal to binary conversion

---

DIRECTORY.md
conversions/hexadecimal_to_octal.dart

Added hex to oct conversion

---

graphs/depth_first_search.dart

Created Graph as Adjacency List representation using HashMap to store nodes as Keys and values as Dynamic List
Depth-first Search and helper methods
Added in test cases

Depth First Search implementation Dart:

---

graphs/breadth_first_search.dart

Implemented BFS in the dart.
Added in test cases

Breadth first search Dart implementation

---

DIRECTORY.md
conversions/octal_to_decimal.dart

Added octal to decimal conversion

---

DIRECTORY.md
conversions/octal_to_hexadecimal.dart

Added oct to hex conversion

---

array/validate_subsequence.dart

Implemented the validating subsequence implementation in dart
Added test cases.

Added the validating array sub-sequence in dart

---

maths/fibonacci_dynamic_programming.dart

Added implementation for Finding Nth Fibonacci Number using Dynamic Programming

---

data_structures/quad_tree/quad_tree.dart

addresses feedback from original quad tree pr.

make private globals const

---

project_euler/problem_10/sol10.dart

Project Euler Problem 10: https://projecteuler.net/problem=10
Summation of primes
The sum of the primes below 10 is 2 + 3 + 5 + 7 = 17.
Find the sum of all the primes below two million.

Added Euler Project 10

---

project_euler/problem_12/sol12.dart

Added Project Euler 12

---

sort/radix_sort.dart

Radix Sort .
Added in test cases

Radix Sort

---

backtracking/open_knight_tour.dart

feat: added open knight tour algorithm

---

dynamic_programming/01knapsack_recursive.dart

Added the recursive implementation of the 01 knapsack problem

Added Knapsack Problem (recursive Solution)

---

conversions/binary_to_decimal.dart
conversions/hexadecimal_to_decimal.dart
data_structures/Queue/List_Queue.dart
dynamic_programming/01knapsack_recursive.dart
pubspec.yaml
search/interpolation_Search.dart
sort/gnome_Sort.dart
sort/heap_Sort.dart

Corrected some typos as specified [here](https://github.com/TheAlgorithms/Dart/issues/97)

Correcting typos

---

chinese_remainder_theorem/chinese_remainder_theorem.dart

* [*] Add an algorithm?
* [*] I have read [CONTRIBUTING.md](https://github.com/TheAlgorithms/Dart/blob/master/CONTRIBUTING.md).
* [*] I know that pull requests will not be merged if they fail the automated tests.

adding chinese remainder theorem

---

pubspec.yaml

Fixed Issue with Dart test coverage.
Updated the outdated test coverage packages.

Fixes #174

---

array/sorted_squared_array.dart

Sorted Squared Array

---

array/two_sum.dart

Checks if there are two numbers in the array whose sum is equal to given number

Two Sum Algorithm problem

---

project_euler/problem_20/sol20.dart

Implement solution 20 for project euler

---

sort/count_sort.dart

- Added counting sort algorithm in the `sort` directory.
- The algorithm can be implemented for array containing both positive as well as negative integers.
- Have run `dart analyze` and `dart format` .
- This is my first PR here. I apologize in advance for anything against the format.

added count_sort.dart

---

data_structures/Stack/Array_Stack.dart

Fix test cases for array stack

---

conversions/binary_to_decimal.dart

Fix conversion/binary decimal

---

conversions/binary_to_hexadecimal.dart
conversions/binary_to_octal.dart
data_structures/Stack/Array_Stack.dart

Update tests, Fix Linter errors

---

dynamic_programming/longest_common_subsequence.dart

* [x ] I have read [CONTRIBUTING.md](https://github.com/TheAlgorithms/Dart/blob/master/CONTRIBUTING.md).
* [x ] This pull request is all my own work -- I have not plagiarized.
* [ x] I know that pull requests will not be merged if they fail the automated tests.
* [ x] This PR only changes one algorithm file.  To ease review, please open separate PRs for separate algorithms.
* [ x] All new Dart files are placed inside an existing directory.

added dp alogorithm longest common subsequence in dart

---

graphs/breadth_first_search.dart

`Fixes: #198`

---

dynamic_programming/longest_common_substring.dart

added longest common substring

---

data_structures/binary_tree/binary_tree_traversal.dart

Implemented Level Order traversal and fixed:List.List deprecation warnings in .\data_structures\binary_tree\binary_tree_traversal.dart

---

trees/path_sum.dart

Implements the Path Sum in tree question from Leetcode.

Binary Tree Path Sum

---

sort/merge_sort.dart

Reverts TheAlgorithms/Dart#213

Revert "Add test case to merge sort"

---

sort/merge_sort.dart

Add test cases to merge sort

---

array/car_pool.dart

Car pooling Timeline array problem

---

strings/isomorphic_strings.dart

Problem statement: https://leetcode.com/problems/isomorphic-strings/

Isomorphic strings.

---

data_structures/linked_list/merge_sorted_list.dart
graphs/area_of_island.dart

https://leetcode.com/problems/merge-two-sorted-lists/

Merge sorted linked list

---

.github/workflows/dart_test_analyze_format.yml

Running dart format before test will stop the workflow before executing the complete test

Run dart format before test
